query C {
  cars {
    id
    name
    charger {
      id
      serialNumber
    }
  }
}

query CH {
  chargers {
    id
    serialNumber
    cars{
      id
      name
    }
  }
}

mutation UC($car:CarInput!) {
  updateCar(car: $car){
    id
    chargerId
  }
}

// variables
{
"car": {
"id": "ebf93172-1419-4a5c-9200-b0a600f1f7f9",
"name": "Hot Thunder",
"registrationNumber": "RCA936",
"chargerId": "609a7fe7-0aad-46af-ab64-b0a600f3d821"
}
}