query C {
  cars{
    id
    registrationNumber

  }
}

mutation AC($car: CarInput!) {
  addCar(car: $car) {
    id
    registrationNumber
  }
}

mutation UC($updateCar: CarUpdateInput!) {
  updateCar(car: $updateCar) {
    id
    registrationNumber
    chargerId
  }
}

mutation DU($deleteCarId: String!){
  deleteCar(id: $deleteCarId)
}

query CH {
  chargers {
    id
    serialNumber

    cars {
      id
      registrationNumber
    }
    user{
      firstName
    }
  }
}

mutation ACH($charger: ChargerInput!) {
  addCharger(charger: $charger) {
    id
    serialNumber
  }
}

mutation UCH($updateCharger: ChargerUpdateInput!) {
  updateCharger(charger: $updateCharger) {
   id
   serialNumber
  }
}

mutation DU($deleteCarId: String!){
  deleteCar(id: $deleteCarId)
}


query CH {
  chargers {
    id
    serialNumber
    cars {
      id
      registrationNumber
    }
  }
}

mutation ACH($charger: ChargerInput!) {
  addCharger(charger: $charger) {
    id
    serialNumber
  }
}

mutation UCH($updateCharger: ChargerUpdateInput!) {
  updateCharger(charger: $updateCharger) {
   id
   serialNumber
  }
}

mutation DU($deleteCarId: String!){
  deleteCar(id: $deleteCarId)
}

